import React, { createContext, useContext, useState } from "react";

export type Language = "es" | "en" | "it" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const TRANSLATIONS: Record<Language, Record<string, any>> = {
  es: {
    nav: {
      inicio: "Inicio",
      filosofia: "Filosofía",
      servicios: "Servicios Técnicos",
      portfolio: "Portafolio",
      planner: "Asesor AI",
      contacto: "Contacto",
    },
    hero: {
      tagline: "Arquitectura con Sentido & Alta Ingeniería",
      heading: "UNO Arquitectos",
      subheading: "Tu proyecto puede hacerse. Te decimos cómo y cuánto. Soluciones de arquitectura residencial premium, ingeniería estructural sismorresistente y gestión de licencias para el subsuelo kárstico de la Riviera Maya.",
      scroll: "Deslice para explorar",
      metricBuild: "Metros Construidos",
      metricProjects: "Proyectos Entregados",
      metricDirectors: "Directores de Obra",
    },
    filosofia: {
      purpose: "Hacer arquitectura con sentido, honestidad y pies en la tierra.",
      tagline: "Nuestra Filosofía",
      heading: "Criterio, Materia y Estructura Sólida",
      p1: "UNO Arquitectos es una firma boutique de arquitectura e ingeniería residencial premium establecida en la Riviera Maya. Desarrollamos proyectos integrales donde la elegancia formal responde a la función real, la eficiencia térmica y la precisión estructural sobre terreno kárstico.",
      p2: "Especialistas en la integración de acabados autóctonos como el Chukum natural y maderas duras certificadas de Tzalam y Parota, combinadas con concreto aparente. Cada volumen se proyecta para optimizar la ventilación pasiva y convivir armónicamente con la selva tropical.",
      p3: "Garantizamos la máxima certidumbre técnica y jurídica en cada obra mediante cálculos sismorresistentes, pilotaje especializado y estricto apego a las normativas de conservación ambiental en Tulum, Cancún y Playa del Carmen.",
      valSust: "Sostenibilidad Pasiva",
      valSustDesc: "Estrategias de confort térmico pasivo, captación pluvial eficiente y energías limpias para el clima tropical.",
      valIntegr: "Respeto al Entorno",
      valIntegrDesc: "Integración topográfica, conservación del manto freático y preservación de la vegetación nativa.",
      valIng: "Alta Ingeniería",
      valIngDesc: "Estructuras sismorresistentes calculadas para vientos de tormenta y cimentaciones estables sobre cenotes y suelo kárstico.",
    },
    metrics: {
      m1Val: "15+",
      m1Title: "Años de Trayectoria",
      m1Desc: "Liderando alta ingeniería estructural en el sureste mexicano.",
      m2Val: "80K+",
      m2Title: "m² Proyectados",
      m2Desc: "Diseñados, calculados y construidos con precisión técnica.",
      m3Val: "100%",
      m3Title: "Viabilidad Legal",
      m3Desc: "Aprobación y gestoría de licencias de construcción y manifiestos ambientales.",
      m4Val: "+150",
      m4Title: "Clientes de Élite",
      m4Desc: "Residencias boutique exclusivas en Tulum, Cancún y CDMX.",
    },
    servicios: {
      tagline: "Proceso de Trabajo",
      heading: "Servicios Técnicos Integrales",
      desc: "Gestión técnica integral desde la viabilidad legal y el análisis geotécnico de suelo hasta la entrega final de la obra, coordinada por directores de obra experimentados.",
      phases: {
        f0: "Preconstrucción y Permisos",
        f0Desc: "Estudios de viabilidad legal y técnica, gestoría ambiental (MIA), tramitación de licencias municipales de construcción, fusiones y autorizaciones previas.",
        f1: "Ingeniería Estructural",
        f1Desc: "Estudio geotécnico de suelo kárstico, cálculo de cargas dinámicas y cimentaciones sismorresistentes con sistemas de pilotaje profundo.",
        f2: "Obra Gris y Concreto",
        f2Desc: "Construcción de volúmenes monolíticos en concreto aparente de alta especificación y colados texturizados artesanales.",
        f3: "Acabados y Materialidad",
        f3Desc: "Aplicación de Chukum artesanal continuo, carpintería técnica en maderas tropicales certificadas (Tzalam/Parota) e iluminación arquitectónica.",
        f4: "Entrega de Obra",
        f4Desc: "Integración de instalaciones técnicas, domótica, paisajismo nativo de barrera y entrega formal lista para habitar.",
      },
      cta: "Planificar Mi Proyecto",
    },
    portfolio: {
      tagline: "Obras Realizadas",
      heading: "Proyectos de Arquitectura e Ingeniería",
      desc: "Explore nuestro portafolio residencial en la Riviera Maya. Cada obra demuestra soluciones de alta ingeniería y materialidad integradas al ecosistema.",
      all: "Todos los Proyectos",
      f_estructural: "Fase Estructural",
      f_gris: "Obra Gris",
      f_acabados: "Acabados",
      f_entregado: "Entregados",
      location: "Ubicación",
      year: "Año",
      status: "Estado",
      viewDetails: "Ver Ficha Técnica",
      carouselPrev: "Anterior",
      carouselNext: "Siguiente",
      items: {
        villaChukumDesc: "Residencia boutique en la selva de Tulum terminada en Chukum natural continuo en muros interiores y exteriores. Excelente regulación térmica pasiva y bajo mantenimiento.",
        casaTzalamDesc: "Diseño residencial asimétrico con terrazas en cantiléver. Madera de Tzalam local certificada combinada con muros monolíticos de concreto aparente lavado.",
        cenoteSanctuaryDesc: "Hito de ingeniería estructural adaptado a la geología kárstica. Estructura cimentada sobre pilotes de concreto armado que respetan el flujo subterráneo de cenotes.",
        residenciaSascabDesc: "Proyecto residencial de 350m² con concreto aparente entablado texturizado artesanalmente. Orientación bioclimática para captura de brisas marinas.",
        kaanVillaDesc: "Residencia costera con cimentación profunda y ventanales estructurales resistentes a vientos de tormenta tropical. Piscina integrada al paisaje marino.",
      }
    },
    planner: {
      tagline: "Estudio Conceptual",
      heading: "Asesoría Técnica Digital",
      desc: "Defina las características de su lote o proyecto. Nuestro motor calcula parámetros técnicos, costos reales de construcción y materialidad para Tulum y la Riviera Maya.",
      formTitle: "Parámetros del Proyecto",
      projName: "Nombre del Proyecto",
      projNamePlaceholder: "ej. Casa Tulum, Proyecto Cancún",
      locationLabel: "Ubicación",
      areaLabel: "Área Deseada de Construcción",
      esteticaLabel: "Criterio Estético",
      fasesLabel: "Fases Requeridas",
      lujoLabel: "Nivel de Especificación",
      specsLabel: "Requerimientos Particulares",
      specsPlaceholder: "ej. Muros de Chukum, ventilación cruzada y paneles solares.",
      btnSubmit: "Generar Propuesta Técnica",
      btnSubmitting: "Calculando...",
      savedInquiries: "Propuestas Guardadas",
      noPropTitle: "Análisis Arquitectónico",
      noPropDesc: "Ingrese los datos de su terreno. Obtendrá un reporte con parámetros técnicos, materiales recomendados y rango presupuestal estimado.",
      noPropCardTitle: "✓ Precisión Técnica",
      noPropCardDesc: "Reportes parametrizados con costos reales de construcción para Tulum, Cancún y Playa del Carmen.",
      loadingTitle: "Analizando Proyecto",
      loadingSteps: [
        "Analizando orientación solar y viento...",
        "Seleccionando materiales locales (Chukum, Tzalam, Piedra)...",
        "Calculando cimentación para suelo kárstico...",
        "Diseñando estrategias bioclimáticas pasivas...",
        "Estimando presupuesto por fases de obra..."
      ],
      conceptBoard: "Reporte Técnico AI",
      stylePrefix: "Criterio",
      downloadDossier: "Descargar Reporte PDF",
      dossierReady: "¡Reporte Generado!",
      dossierReadyDesc: "Se ha generado la propuesta técnica inicial. Se ha compartido una copia con nuestro equipo de ingeniería.",
      close: "Cerrar",
      visionLabel: "Integración al Entorno",
      adaptationLabel: "Criterio Arquitectónico",
      materialsLabel: "Materiales Sugeridos",
      sustainabilityLabel: "Estrategias Pasivas",
      budgetLabel: "Presupuesto Estimado",
      budgetRange: "Rango Estimado",
      directorsLabel: "Notas del Director de Obra",
      ctaQuestion: "¿Desea agendar una revisión presencial de su proyecto en Tulum o CDMX?",
      ctaBtn: "Agendar Cita Técnica",
    },
    contacto: {
      tagline: "Contacto y Atenciones",
      heading: "Comience su Proyecto",
      desc: "Nuestros directores técnicos atienden citas presenciales en nuestro showroom de Tulum y oficina en Polanco, CDMX.",
      conversionTagline: "Diseño con sentido. Construcción con criterio.",
      showroomTulum: "Showroom Tulum",
      showroomTulumAddr: "Av. Boca Paila Km 4.5, Zona Costera, Tulum, Q. Roo",
      cdmxOffice: "Oficina CDMX",
      cdmxOfficeAddr: "Campos Elíseos 385, Polanco III Secc, CDMX",
      workHours: "Lunes a Sábado: 9:00 AM - 6:00 PM",
      formHeading: "Solicitud de Consulta Técnica",
      formSubheading: "Complete sus datos y un especialista técnico se pondrá en contacto.",
      fullName: "Nombre Completo",
      fullNamePlaceholder: "ej. Ing. Fernando Gómez",
      phone: "Teléfono / WhatsApp",
      phonePlaceholder: "ej. +52 984 123 4567",
      email: "Correo Electrónico",
      emailPlaceholder: "ej. contacto@empresa.com",
      additionalMsg: "Detalles del Terreno o Proyecto",
      additionalMsgPlaceholder: "Describa la ubicación, m² aproximados y fechas estimadas.",
      btnSubmit: "Enviar Solicitud",
      successTitle: "Mensaje Recibido",
      successDesc: "Gracias por escribir a UNO Arquitectos. Nos pondremos en contacto en menos de 24 horas hábiles.",
      successAnother: "Enviar otro mensaje",
    },
    footer: {
      desc: "Firma boutique de arquitectura e ingeniería residencial en la Riviera Maya. Hacemos arquitectura con sentido, honestidad y pies en la tierra.",
      sections: "Navegación",
      presence: "Ubicaciones",
      attention: "Citas Técnicas",
      attentionDesc: "Para agendar visitas a obra o terrenos en Quintana Roo, envíe una solicitud en la sección de contacto.",
      scrollTop: "Subir",
      privacy: "Aviso de Privacidad",
      terms: "Términos de Servicio",
      rights: "Todos los derechos reservados.",
    }
  },
  en: {
    nav: {
      inicio: "Home",
      filosofia: "Philosophy",
      servicios: "Technical Services",
      portfolio: "Portfolio",
      planner: "AI Advisor",
      contacto: "Contact",
    },
    hero: {
      tagline: "Architecture with Purpose & High Engineering",
      heading: "UNO Arquitectos",
      subheading: "Your project can be built. We tell you how and how much. Honest premium residential architecture, seismic engineering, and environmental permitting for the karstic soil of the Riviera Maya.",
      scroll: "Scroll to explore",
      metricBuild: "Sqm Constructed",
      metricProjects: "Delivered Projects",
      metricDirectors: "Site Directors",
    },
    filosofia: {
      purpose: "Architecture with purpose, honesty, and grounded engineering.",
      tagline: "Our Philosophy",
      heading: "Criteria, Materiality & Solid Engineering",
      p1: "UNO Arquitectos is a boutique residential architecture and high structural engineering firm based in the Riviera Maya. We design and build projects where formal beauty directly answers to real function, thermal efficiency, and karstic soil engineering.",
      p2: "Specializing in native materials such as natural Chukum plaster and certified Tzalam and Parota tropical hardwoods, combined with architectural exposed concrete. Each volume optimizes passive cross-ventilation and coexists harmoniously with the tropical jungle.",
      p3: "We guarantee technical and legal certainty for every build through seismic-resistant calculations, deep piling systems, and strict compliance with environmental regulations in Tulum, Cancun, and Playa del Carmen.",
      valSust: "Passive Sustainability",
      valSustDesc: "Passive thermal comfort, rainwater harvesting, and clean solar energy for tropical climates.",
      valIntegr: "Environmental Respect",
      valIntegrDesc: "Topographical integration, water table protection, and native jungle flora preservation.",
      valIng: "High Structural Engineering",
      valIngDesc: "Storm-wind calculated structures and stable foundations over cenotes and karstic subsoil.",
    },
    metrics: {
      m1Val: "15+",
      m1Title: "Years of Experience",
      m1Desc: "Leading high structural engineering in the Mexican Southeast.",
      m2Val: "80K+",
      m2Title: "Sqm Projected",
      m2Desc: "Designed, calculated, and built with technical precision.",
      m3Val: "100%",
      m3Title: "Legal Feasibility",
      m3Desc: "Agile environmental licensing and municipal construction permits.",
      m4Val: "+150",
      m4Title: "Elite Clients",
      m4Desc: "Exclusive boutique residential properties in Tulum, Cancun, and CDMX.",
    },
    servicios: {
      tagline: "Work Process",
      heading: "Comprehensive Technical Services",
      desc: "End-to-end technical management from legal feasibility and soil analysis to final construction delivery, led by experienced site directors.",
      phases: {
        f0: "Preconstruction & Permitting",
        f0Desc: "Legal and technical feasibility studies, environmental permits (MIA), municipal construction licensing, land division, and pre-construction authorization.",
        f1: "Structural Engineering",
        f1Desc: "Karstic soil geotechnical study, dynamic load calculation, and earthquake-resistant deep pile foundations.",
        f2: "Gray Shell & Concrete",
        f2Desc: "Monolithic construction in high-specification exposed concrete and artisanal textured castings.",
        f3: "Finishes & Materials",
        f3Desc: "Continuous hand-applied Chukum plaster, technical carpentry in certified tropical woods (Tzalam/Parota), and architectural lighting.",
        f4: "Project Delivery",
        f4Desc: "Integration of technical utilities, home automation, native dune/jungle landscaping, and formal turnkey delivery.",
      },
      cta: "Plan My Project",
    },
    portfolio: {
      tagline: "Featured Works",
      heading: "Architecture & Engineering Portfolio",
      desc: "Explore our residential builds across the Riviera Maya. Every project showcases high engineering and native materials integrated into the ecosystem.",
      all: "All Projects",
      f_estructural: "Structural Phase",
      f_gris: "Gray Shell",
      f_acabados: "Finishes",
      f_entregado: "Delivered",
      location: "Location",
      year: "Year",
      status: "Status",
      viewDetails: "View Technical Sheet",
      carouselPrev: "Previous",
      carouselNext: "Next",
      items: {
        villaChukumDesc: "Boutique villa in the Tulum jungle finished in continuous natural Chukum across interior and exterior walls. Superior passive climate regulation and minimal maintenance.",
        casaTzalamDesc: "Asymmetrical residential design featuring cantilevered terraces. Certified local Tzalam hardwood combined with washed exposed concrete walls.",
        cenoteSanctuaryDesc: "Structural engineering milestone adapted to karstic subsoil. Structure anchored on reinforced concrete piles respecting subterranean cenote flows.",
        residenciaSascabDesc: "350sqm residential project in advanced gray shell. Artisanal board-formed exposed concrete texture with bioclimatic orientation for sea breezes.",
        kaanVillaDesc: "Coastal residence featuring deep foundation engineering and hurricane-rated structural glass. Infinity pool integrated into the ocean landscape.",
      }
    },
    planner: {
      tagline: "Conceptual Study",
      heading: "Digital Technical Consultation",
      desc: "Define your lot or project parameters. Our smart engine calculates technical specs, real construction costs, and native materiality for Tulum and the Riviera Maya.",
      formTitle: "Project Parameters",
      projName: "Project Name",
      projNamePlaceholder: "e.g., Casa Tulum, Cancun Project",
      locationLabel: "Location",
      areaLabel: "Desired Building Area",
      esteticaLabel: "Aesthetic Direction",
      fasesLabel: "Required Phases",
      lujoLabel: "Specification Level",
      specsLabel: "Specific Requirements",
      specsPlaceholder: "e.g., Chukum walls, cross ventilation, and solar panels.",
      btnSubmit: "Generate Technical Proposal",
      btnSubmitting: "Calculating...",
      savedInquiries: "Saved Proposals",
      noPropTitle: "Architectural Analysis",
      noPropDesc: "Enter your land details to receive a technical report with material recommendations and estimated budget ranges.",
      noPropCardTitle: "✓ Technical Precision",
      noPropCardDesc: "Parameterized reports based on real construction costs in Tulum, Cancun, and Playa del Carmen.",
      loadingTitle: "Analyzing Project",
      loadingSteps: [
        "Analyzing solar orientation and wind patterns...",
        "Selecting native materials (Chukum, Tzalam, Stone)...",
        "Calculating karstic soil foundation engineering...",
        "Designing passive bioclimatic strategies...",
        "Estimating phase-by-phase construction budget..."
      ],
      conceptBoard: "AI Technical Report",
      stylePrefix: "Criteria",
      downloadDossier: "Download PDF Report",
      dossierReady: "Report Generated!",
      dossierReadyDesc: "Initial technical proposal generated. A copy has been shared with our structural engineering team.",
      close: "Close",
      visionLabel: "Ecosystem Integration",
      adaptationLabel: "Architectural Criteria",
      materialsLabel: "Suggested Materials",
      sustainabilityLabel: "Passive Strategies",
      budgetLabel: "Estimated Budget",
      budgetRange: "Estimated Range",
      directorsLabel: "Site Director's Notes",
      ctaQuestion: "Would you like to schedule an in-person review in Tulum or CDMX?",
      ctaBtn: "Schedule Technical Meeting",
    },
    contacto: {
      tagline: "Contact & Consultations",
      heading: "Start Your Project",
      desc: "Our technical directors host in-person consultations at our Tulum showroom and Polanco CDMX office.",
      conversionTagline: "Diseño con sentido. Construcción con criterio.",
      showroomTulum: "Showroom Tulum",
      showroomTulumAddr: "Av. Boca Paila Km 4.5, Coastal Zone, Tulum, Q. Roo",
      cdmxOffice: "CDMX Office",
      cdmxOfficeAddr: "Campos Elíseos 385, Polanco III Secc, CDMX",
      workHours: "Monday to Saturday: 9:00 AM - 6:00 PM",
      formHeading: "Technical Consultation Request",
      formSubheading: "Complete your details and a technical specialist will contact you.",
      fullName: "Full Name",
      fullNamePlaceholder: "e.g., Eng. Fernando Gomez",
      phone: "Phone / WhatsApp",
      phonePlaceholder: "e.g., +52 984 123 4567",
      email: "Email Address",
      emailPlaceholder: "e.g., contact@company.com",
      additionalMsg: "Plot or Project Details",
      additionalMsgPlaceholder: "Describe location, estimated sqm, and target dates.",
      btnSubmit: "Submit Request",
      successTitle: "Message Received",
      successDesc: "Thank you for writing to UNO Arquitectos. We will reach out within 24 business hours.",
      successAnother: "Send another message",
    },
    footer: {
      desc: "Boutique residential architecture and engineering firm in the Riviera Maya. Architecture with purpose, honesty, and grounded engineering.",
      sections: "Navigation",
      presence: "Locations",
      attention: "Technical Appointments",
      attentionDesc: "To schedule site or plot visits in Quintana Roo, please submit a request in the contact section.",
      scrollTop: "Top",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      rights: "All rights reserved.",
    }
  },
  it: {
    nav: {
      inicio: "Inizio",
      filosofia: "Filosofia",
      servicios: "Servizi Tecnici",
      portfolio: "Portfolio",
      planner: "Consulente AI",
      contacto: "Contatti",
    },
    hero: {
      tagline: "Architettura con Senso & Alta Ingegneria",
      heading: "UNO Arquitectos",
      subheading: "Il tuo progetto può essere realizzato. Ti diciamo come e quanto costa. Soluzioni di architettura residenziale premium e ingegneria sismoresistente per il terreno carsico della Riviera Maya.",
      scroll: "Scorri per esplorare",
      metricBuild: "Mq Costruiti",
      metricProjects: "Progetti Consegnati",
      metricDirectors: "Direttori di Cantiere",
    },
    filosofia: {
      purpose: "Fare architettura con senso, onestà e piedi per terra.",
      tagline: "La Nostra Filosofia",
      heading: "Criterio, Materia e Struttura Solida",
      p1: "UNO Arquitectos è uno studio boutique di architettura residenziale premium ed ingegneria strutturale radicato nella Riviera Maya. Sviluppiamo progetti integrali dove la bellezza formale risponde alla funzione reale e all'ingegneria strutturale.",
      p2: "Specialisti nell'integrazione di finiture autoctone come il Chukum naturale e legni pregiati certificati (Tzalam e Parota) abbinati al cemento armato a vista. Ogni volume è progettato per ottimizzare la ventilazione passiva e coesistere con la giungla tropicale.",
      p3: "Garantiamo la massima certezza tecnica e legale in ogni opera attraverso calcoli sismoresistenti, palificazione specializzata e rispetto delle normative ambientali a Tulum, Cancún e Playa del Carmen.",
      valSust: "Sostenibilità Passiva",
      valSustDesc: "Strategie di comfort termico passivo, raccolta dell'acqua piovana ed energia pulita.",
      valIntegr: "Rispetto dell'Ambiente",
      valIntegrDesc: "Integrazione topografica, tutela della falda acquifera e conservazione della flora nativa.",
      valIng: "Alta Ingegneria",
      valIngDesc: "Strutture calcolate per venti ciclonici e fondazioni stabili su cenote e terreno carsico.",
    },
    metrics: {
      m1Val: "15+",
      m1Title: "Anni di Esperienza",
      m1Desc: "Leader nell'alta ingegneria strutturale nel sud-est messicano.",
      m2Val: "80K+",
      m2Title: "Mq Progettati",
      m2Desc: "Progettati, calcolati e costruiti con precisione tecnica.",
      m3Val: "100%",
      m3Title: "Fattibilità Legale",
      m3Desc: "Approvazione rapida di licenze edilizie e autorizzazioni ambientali.",
      m4Val: "+150",
      m4Title: "Clienti d'Élite",
      m4Desc: "Proprietà residenziali boutique esclusive a Tulum, Cancún e CDMX.",
    },
    servicios: {
      tagline: "Processo di Lavoro",
      heading: "Servizi Tecnici Integrali",
      desc: "Gestione tecnica completa dalla fattibilità legale all'analisi del terreno fino alla consegna finale dell'opera, coordinata da direttori di cantiere esperti.",
      phases: {
        f0: "Pre-costruzione e Permessi",
        f0Desc: "Studi di fattibilità legale e tecnica, gestione ambientale, pratiche per licenze edilizie municipali e autorizzazioni preliminari.",
        f1: "Ingegneria Strutturale",
        f1Desc: "Studio geotecnico del terreno carsico, calcolo dei carichi dinamici e fondazioni sismoresistenti con palificazione profonda.",
        f2: "Lavori al Grezzo e Cemento",
        f2Desc: "Costruzione di volumi monolitici in cemento a vista ad alta specifica e getti testurizzati artigianali.",
        f3: "Finiture e Materialità",
        f3Desc: "Applicazione artigianale di Chukum continuo, falegnameria tecnica in legni tropicali certificati (Tzalam/Parota) e illuminazione architetturale.",
        f4: "Consegna dell'Opera",
        f4Desc: "Integrazione di impianti tecnici, domotica, paesaggistica nativa e consegna formale pronta da abitare.",
      },
      cta: "Pianifica il Mio Progetto",
    },
    portfolio: {
      tagline: "Opere Realizzate",
      heading: "Progetti di Architettura e Ingegneria",
      desc: "Esplora il nostro portfolio residenziale nella Riviera Maya. Ogni opera dimostra soluzioni d'ingegneria e materiali integrati nell'ecosistema.",
      all: "Tutti i Progetti",
      f_estructural: "Fase Strutturale",
      f_gris: "Lavori al Grezzo",
      f_acabados: "Finiture",
      f_entregado: "Consegnati",
      location: "Località",
      year: "Anno",
      status: "Stato",
      viewDetails: "Vedi Scheda Tecnica",
      carouselPrev: "Precedente",
      carouselNext: "Successivo",
      items: {
        villaChukumDesc: "Villa boutique nella giungla di Tulum rifinita in Chukum naturale continuo su pareti interne ed esterne. Ottima regolazione termica passiva e manutenzione minima.",
        casaTzalamDesc: "Design residenziale asimmetrico con terrazze a sbalzo. Legno di Tzalam locale certificato abbinato a pareti monolitiche in cemento a vista lavato.",
        cenoteSanctuaryDesc: "Pietra miliare dell'ingegneria strutturale adattata alla geologia carsica. Struttura ancorata su pali in cemento armato che rispettano i flussi dei cenote sotterranei.",
        residenciaSascabDesc: "Progetto residenziale di 350 mq in fase avanzata al grezzo. Cemento a vista testurizzato con assi di legno e orientamento bioclimatico per le brezze marine.",
        kaanVillaDesc: "Residenza costiera con fondazioni profonde e vetrate strutturali resistenti ai venti di tempesta tropicale. Piscina integrata nel paesaggio marino.",
      }
    },
    planner: {
      tagline: "Studio Concettuale",
      heading: "Consulenza Tecnica Digitale",
      desc: "Definisci i parametri del tuo lotto o progetto. Il nostro motore calcola specifiche tecniche, costi reali di costruzione e materialità per Tulum e la Riviera Maya.",
      formTitle: "Parametri del Progetto",
      projName: "Nome del Progetto",
      projNamePlaceholder: "es. Casa Tulum, Progetto Cancún",
      locationLabel: "Posizione",
      areaLabel: "Area di Costruzione Desiderata",
      esteticaLabel: "Criterio Estetico",
      fasesLabel: "Fasi Richieste",
      lujoLabel: "Livello di Specifica",
      specsLabel: "Requisiti Particolari",
      specsPlaceholder: "es. Pareti in Chukum, ventilazione incrociata e pannelli solari.",
      btnSubmit: "Genera Proposta Tecnica",
      btnSubmitting: "Calcolo in corso...",
      savedInquiries: "Proposte Salvate",
      noPropTitle: "Analisi Architettonica",
      noPropDesc: "Inserisci i dati del tuo terreno per ricevere un report con parametri tecnici, materiali raccomandati e stima del budget.",
      noPropCardTitle: "✓ Precisione Tecnica",
      noPropCardDesc: "Report parametrizzati con costi reali di costruzione per Tulum, Cancún e Playa del Carmen.",
      loadingTitle: "Analisi del Progetto",
      loadingSteps: [
        "Analisi dell'orientamento solare e dei venti...",
        "Selezione dei materiali locali (Chukum, Tzalam, Pietra)...",
        "Calcolo delle fondazioni per terreno carsico...",
        "Progettazione di strategie bioclimatiche passive...",
        "Stima del budget per fasi di cantiere..."
      ],
      conceptBoard: "Report Tecnico AI",
      stylePrefix: "Criterio",
      downloadDossier: "Scarica Report PDF",
      dossierReady: "Report Generato!",
      dossierReadyDesc: "La proposta tecnica iniziale è pronta. Una copia è stata condivisa con il nostro team d'ingegneria.",
      close: "Chiudi",
      visionLabel: "Integrazione con l'Ambiente",
      adaptationLabel: "Criterio Architettonico",
      materialsLabel: "Materiali Suggeriti",
      sustainabilityLabel: "Strategie Passive",
      budgetLabel: "Budget Stimato",
      budgetRange: "Intervallo Stimato",
      directorsLabel: "Note del Direttore di Cantiere",
      ctaQuestion: "Vuoi prenotare una revisione di persona del tuo progetto a Tulum o CDMX?",
      ctaBtn: "Prenota Incontro Tecnico",
    },
    contacto: {
      tagline: "Contatti e Consulenze",
      heading: "Inizia il Tuo Progetto",
      desc: "I nostri direttori tecnici ricevono su appuntamento presso lo showroom di Tulum e l'ufficio di Polanco, CDMX.",
      conversionTagline: "Diseño con sentido. Construcción con criterio.",
      showroomTulum: "Showroom Tulum",
      showroomTulumAddr: "Av. Boca Paila Km 4.5, Zona Costiera, Tulum, Q. Roo",
      cdmxOffice: "Ufficio CDMX",
      cdmxOfficeAddr: "Campos Elíseos 385, Polanco III Secc, CDMX",
      workHours: "Lunedì al Sabato: 9:00 - 18:00",
      formHeading: "Richiesta di Consulenza Tecnica",
      formSubheading: "Compila i tuoi dati e uno specialista tecnico ti contatterà.",
      fullName: "Nome Completo",
      fullNamePlaceholder: "es. Ing. Fernando Gómez",
      phone: "Telefono / WhatsApp",
      phonePlaceholder: "es. +52 984 123 4567",
      email: "Indirizzo Email",
      emailPlaceholder: "es. contatto@azienda.com",
      additionalMsg: "Dettagli del Terreno o Progetto",
      additionalMsgPlaceholder: "Descrivi la posizione, i mq stimati e le date previste.",
      btnSubmit: "Invia Richiesta",
      successTitle: "Messaggio Ricevuto",
      successDesc: "Grazie per aver scritto a UNO Arquitectos. Ti contatteremo entro 24 ore lavorative.",
      successAnother: "Invia un altro messaggio",
    },
    footer: {
      desc: "Studio boutique di architettura residenziale ed ingegneria nella Riviera Maya. Architettura con senso, onestà e piedi per terra.",
      sections: "Navigazione",
      presence: "Sedi",
      attention: "Appuntamenti Tecnici",
      attentionDesc: "Per programmare visite a cantieri o terreni a Quintana Roo, invia una richiesta nella sezione contatti.",
      scrollTop: "Su",
      privacy: "Informativa sulla Privacy",
      terms: "Termini di Servizio",
      rights: "Tutti i diritti riservati.",
    }
  },
  fr: {
    nav: {
      inicio: "Accueil",
      filosofia: "Philosophie",
      servicios: "Services Techniques",
      portfolio: "Portfolio",
      planner: "Conseiller IA",
      contacto: "Contact",
    },
    hero: {
      tagline: "Architecture avec Sens & Haute Ingénierie",
      heading: "UNO Arquitectos",
      subheading: "Votre projet peut être réalisé. Nous vous disons comment et combien. Solutions d'architecture résidentielle premium, ingénierie parasismique et permis de construire pour le sol karstique de la Riviera Maya.",
      scroll: "Faites défiler pour explorer",
      metricBuild: "M² Construits",
      metricProjects: "Projets Livrés",
      metricDirectors: "Directeurs de Chantier",
    },
    filosofia: {
      purpose: "Faire de l'architecture avec sens, honnêteté et les pieds sur terre.",
      tagline: "Notre Philosophie",
      heading: "Critère, Matière et Structure Solide",
      p1: "UNO Arquitectos est un studio boutique d'architecture résidentielle premium et de haute ingénierie basé dans la Riviera Maya. Nous développons des projets intégraux où la beauté formelle répond à la fonction réelle et à la précision structurelle.",
      p2: "Spécialistes de l'intégration de matériaux locaux comme le Chukum naturel et les bois nobles certifiés (Tzalam et Parota) combinés au béton armé apparent. Chaque volume optimise la ventilation passive et coexiste avec la jungle tropicale.",
      p3: "Nous garantissons une certitude technique et juridique maximale grâce à des calculs parasismiques, un système de pieux spécialisé et le respect strict des normes environnementales à Tulum, Cancún et Playa del Carmen.",
      valSust: "Durabilité Passive",
      valSustDesc: "Stratégies de confort thermique passif, collecte des eaux de pluie et énergie propre.",
      valIntegr: "Respect de l'Environnement",
      valIntegrDesc: "Intégration topographique, protection de la nappe phréatique et préservation de la flore indigène.",
      valIng: "Haute Ingénierie",
      valIngDesc: "Structures calculées pour les vents cycloniques et fondations stables sur cénotes et sol karstique.",
    },
    metrics: {
      m1Val: "15+",
      m1Title: "Années d'Expérience",
      m1Desc: "Pionnier de la haute ingénierie structurelle dans le sud-est mexicain.",
      m2Val: "80K+",
      m2Title: "M² Projetés",
      m2Desc: "Conçus, calculés et construits avec précision technique.",
      m3Val: "100%",
      m3Title: "Faisabilité Juridique",
      m3Desc: "Approbation rapide des permis de construire et études d'impact environnemental.",
      m4Val: "+150",
      m4Title: "Clients d'Élite",
      m4Desc: "Propriétés résidentielles exclusives à Tulum, Cancún et CDMX.",
    },
    servicios: {
      tagline: "Processus de Travail",
      heading: "Services Techniques Intégraux",
      desc: "Gestion technique intégrale depuis la faisabilité juridique et l'analyse géotechnique du sol jusqu'à la livraison finale du chantier, coordonnée par des directeurs de chantier expérimentés.",
      phases: {
        f0: "Préconstruction & Permis",
        f0Desc: "Études de faisabilité juridique et technique, licences environnementales (MIA), gestion des permis municipaux de construire et autorisations préalables.",
        f1: "Ingénierie Structurelle",
        f1Desc: "Étude géotechnique du sol karstique, calcul des charges dynamiques et fondations parasismiques sur pieux profonds.",
        f2: "Gros Œuvre & Béton",
        f2Desc: "Construction de volumes monolithiques en béton apparent de haute spécification et coulages texturés artisanaux.",
        f3: "Finitions & Matériaux",
        f3Desc: "Application artisanale de Chukum continu, menuiserie technique en bois tropicaux certifiés (Tzalam/Parota) et éclairage architectural.",
        f4: "Livraison du Chantier",
        f4Desc: "Intégration des installations techniques, domotique, aménagement paysager indigène et livraison formelle prête à habiter.",
      },
      cta: "Planifier Mon Projet",
    },
    portfolio: {
      tagline: "Œuvres Livrées",
      heading: "Projets d'Architecture et d'Ingénierie",
      desc: "Explorez notre portfolio résidentiel dans la Riviera Maya. Chaque projet démontre des solutions d'ingénierie et des matériaux intégrés à l'écosystème.",
      all: "Tous les Projets",
      f_estructural: "Phase Structurelle",
      f_gris: "Gros Œuvre",
      f_acabados: "Finitions",
      f_entregado: "Livrés",
      location: "Localisation",
      year: "Année",
      status: "État",
      viewDetails: "Voir la Fiche Technique",
      carouselPrev: "Précédent",
      carouselNext: "Suivant",
      items: {
        villaChukumDesc: "Villa boutique dans la jungle de Tulum finie en Chukum naturel continu sur les murs intérieurs et extérieurs. Excellente régulation thermique passive et entretien minimal.",
        casaTzalamDesc: "Design résidentiel asymétrique avec terrasses en porte-à-faux. Bois de Tzalam certifié local combiné à des murs monolithiques en béton apparent lavé.",
        cenoteSanctuaryDesc: "Étape majeure de l'ingénierie structurelle adaptée à la géologie karstique. Structure ancrée sur des pieux en béton armé respectant les flux des cénotes souterrains.",
        residenciaSascabDesc: "Projet résidentiel de 350m² en phase avancée de gros œuvre. Béton apparent texturé aux planches de bois et orientation bioclimatique pour les brises marines.",
        kaanVillaDesc: "Résidence côtière avec fondations profondes et vitrages structurels résistants aux tempêtes tropicales. Piscine intégrée au paysage marin.",
      }
    },
    planner: {
      tagline: "Étude Conceptuelle",
      heading: "Conseil Technique Digital",
      desc: "Définissez les paramètres de votre terrain ou projet. Notre moteur calcule les spécifications techniques, les coûts réels de construction et la matérialité pour Tulum et la Riviera Maya.",
      formTitle: "Paramètres du Projet",
      projName: "Nom du Projet",
      projNamePlaceholder: "ex. Casa Tulum, Projet Cancun",
      locationLabel: "Localisation",
      areaLabel: "Surface de Construction Souhaitée",
      esteticaLabel: "Orientation Esthétique",
      fasesLabel: "Phases Requises",
      lujoLabel: "Niveau de Spécification",
      specsLabel: "Exigences Particulières",
      specsPlaceholder: "ex. Murs en Chukum, ventilation croisée et panneaux solaires.",
      btnSubmit: "Générer la Proposition Technique",
      btnSubmitting: "Calcul en cours...",
      savedInquiries: "Propositions Enregistrées",
      noPropTitle: "Analyse Architecturale",
      noPropDesc: "Saisissez les données de votre terrain pour recevoir un rapport avec des paramètres techniques, des matériaux recommandés et une estimation budgétaire.",
      noPropCardTitle: "✓ Précision Technique",
      noPropCardDesc: "Rapports paramétrés selon les coûts réels de construction à Tulum, Cancún et Playa del Carmen.",
      loadingTitle: "Analyse du Projet",
      loadingSteps: [
        "Analyse de l'orientation solaire et des vents...",
        "Sélection des matériaux locaux (Chukum, Tzalam, Pierre)...",
        "Calcul des fondations pour sol karstique...",
        "Conception de stratégies bioclimatiques passives...",
        "Estimation du budget par phases de chantier..."
      ],
      conceptBoard: "Rapport Technique IA",
      stylePrefix: "Critère",
      downloadDossier: "Télécharger le Rapport PDF",
      dossierReady: "Rapport Généré !",
      dossierReadyDesc: "La proposition technique initiale est prête. Une copie a été transmise à notre équipe d'ingénierie.",
      close: "Fermer",
      visionLabel: "Intégration à l'Écosystème",
      adaptationLabel: "Critère Architectural",
      materialsLabel: "Matériaux Suggérés",
      sustainabilityLabel: "Stratégies Passives",
      budgetLabel: "Budget Estimé",
      budgetRange: "Fourchette Estimée",
      directorsLabel: "Notes du Directeur de Chantier",
      ctaQuestion: "Souhaitez-vous planifier une révision en personne à Tulum ou CDMX ?",
      ctaBtn: "Planifier un Rendez-vous Technique",
    },
    contacto: {
      tagline: "Contact et Consultations",
      heading: "Commencer Votre Projet",
      desc: "Nos directeurs techniques vous accueillent sur rendez-vous dans notre showroom de Tulum et nos bureaux de Polanco, CDMX.",
      conversionTagline: "Diseño con sentido. Construcción con criterio.",
      showroomTulum: "Showroom Tulum",
      showroomTulumAddr: "Av. Boca Paila Km 4.5, Zone Cotière, Tulum, Q. Roo",
      cdmxOffice: "Bureau CDMX",
      cdmxOfficeAddr: "Campos Elíseos 385, Polanco III Secc, CDMX",
      workHours: "Lundi au Samedi : 9h00 - 18h00",
      formHeading: "Demande de Consultation Technique",
      formSubheading: "Remplissez vos coordonnées et un spécialiste technique vous contactera.",
      fullName: "Nom Complet",
      fullNamePlaceholder: "ex. Ing. Fernando Gómez",
      phone: "Téléphone / WhatsApp",
      phonePlaceholder: "ex. +52 984 123 4567",
      email: "Adresse E-mail",
      emailPlaceholder: "ex. contact@entreprise.com",
      additionalMsg: "Détails du Terrain ou Projet",
      additionalMsgPlaceholder: "Décrivez la localisation, la surface estimée et les dates cibles.",
      btnSubmit: "Envoyer la Demande",
      successTitle: "Message Reçu",
      successDesc: "Merci d'avoir écrit à UNO Arquitectos. Nous vous contacterons sous 24 heures ouvrables.",
      successAnother: "Envoyer un autre message",
    },
    footer: {
      desc: "Studio boutique d'architecture résidentielle et d'ingénierie dans la Riviera Maya. Architecture avec sens, honnêteté et les pieds sur terre.",
      sections: "Navigation",
      presence: "Localisations",
      attention: "Rendez-vous Techniques",
      attentionDesc: "Pour planifier des visites de chantiers ou de terrains dans le Quintana Roo, soumettez une demande dans la section contact.",
      scrollTop: "Haut",
      privacy: "Politique de Confidentialité",
      terms: "Conditions d'Utilisation",
      rights: "Tous droits réservés.",
    }
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("uno_arquitectos_lang");
    if (saved && ["es", "en", "it", "fr"].includes(saved)) {
      return saved as Language;
    }
    return "es";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("uno_arquitectos_lang", lang);
  };

  const t = (keyPath: string) => {
    const keys = keyPath.split(".");
    let current: any = TRANSLATIONS[language];
    for (const key of keys) {
      if (current && key in current) {
        current = current[key];
      } else {
        let fb: any = TRANSLATIONS["es"];
        for (const k of keys) {
          if (fb && k in fb) {
            fb = fb[k];
          } else {
            return keyPath;
          }
        }
        return fb;
      }
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
