import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "es" | "en" | "it" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const TRANSLATIONS: Record<Language, Record<string, any>> = {
  es: {
    nav: {
      inicio: "Inicio",
      filosofia: "Filosofía",
      servicios: "Servicios de Élite",
      portfolio: "Portafolio",
      planner: "Asesor AI",
      contacto: "Contacto",
    },
    hero: {
      tagline: "Arquitectura Brutalista Tropical & Alta Ingeniería",
      heading: "UNO Arquitectos",
      subheading: "Diseño y construcción residencial premium en el Caribe Mexicano. Fusionamos el concreto crudo, el Chukum nativo y maderas exóticas con cimentaciones antisísmicas adaptadas al suelo kárstico de la Riviera Maya.",
      scroll: "Deslice para explorar",
      metricBuild: "Metros Construidos",
      metricProjects: "Proyectos Entregados",
      metricDirectors: "Directores de Obra",
    },
    filosofia: {
      tagline: "Nuestra Filosofía",
      heading: "Armonía, Materia y Estructura Sólida",
      p1: "UNO Arquitectos nació con el firme propósito de redefinir el lujo residencial en la Riviera Maya. Creemos que la arquitectura caribeña no es solo una cuestión de estética exterior, sino una simbiosis absoluta entre el arte formal, el respeto ecosistémico y la precisión de la alta ingeniería estructural.",
      p2: "Nuestros diseños integran técnicas ancestrales mayas como el acabado de Chukum fino y el uso de maderas nobles certificadas (Tzalam y Parota) con modernos muros de concreto armado aparente. Cada volumen se proyecta para maximizar la ventilación pasiva, captar la iluminación natural filtrada y coexistir en equilibrio con la densa selva húmeda y las brisas del mar.",
      p3: "Más allá de lo visual, garantizamos la durabilidad eterna de su patrimonio. Calculamos y ejecutamos cimentaciones sismo-resistentes and sistemas especiales de pilotaje diseñados específicamente para el complejo subsuelo kárstico de la península, respetando rigurosamente los ríos subterráneos y la hidrología local.",
      valSust: "Sostenibilidad",
      valSustDesc: "Estrategias pasivas de confort térmico, captación pluvial de alta eficiencia y paneles solares limpios.",
      valIntegr: "Integración Natural",
      valIntegrDesc: "Respeto total de la topografía selvática y reubicación cuidadosa de la flora endémica local.",
      valIng: "Alta Ingeniería",
      valIngDesc: "Estructuras capaces de soportar vientos huracanados Categoría 5 y cimentaciones estables sobre cenotes.",
    },
    servicios: {
      tagline: "Nuestras Fases de Obra",
      heading: "Servicios Técnicos de",
      desc: "Brindamos una gestión integrada desde la cimentación de alta ingeniería hasta la entrega de llaves. Cada etapa es coordinada por directores técnicos con más de 15 años de experiencia.",
      phases: {
        f1: "Obra Estructural",
        f1Desc: "Análisis geológico de suelo kárstico, cálculo de cargas dinámicas y cimentaciones sismo-resistentes con pilotes profundos.",
        f2: "Obra Gris",
        f2Desc: "Elevación de volúmenes en concreto aparente de alta especificación. Colados texturizados con cimbras de madera enduelada.",
        f3: "Acabados de Lujo",
        f3Desc: "Aplicación artesanal de Chukum, carpintería fina en maderas tropicales resistentes al clima (Tzalam/Parota) e iluminación cálida.",
        f4: "Entrega Llave en Mano",
        f4Desc: "Equipamiento de cocina premium, domótica integrada, paisajismo nativo de regeneración dunar y entrega formal 360°.",
      },
      cta: "Planificar Mi Proyecto",
    },
    portfolio: {
      tagline: "Obras Destacadas",
      heading: "Portafolio de Arquitectura de Vanguardia",
      desc: "Explore nuestras obras en la Riviera Maya. Cada proyecto representa un hito de integración natural y sofisticación material.",
      all: "Todos los Proyectos",
      f_estructural: "Fase Estructural",
      f_gris: "Obra Gris",
      f_acabados: "Acabados de Lujo",
      f_entregado: "Proyectos Entregados",
      location: "Ubicación",
      year: "Año de Obra",
      status: "Estado de Obra",
      viewDetails: "Ver Detalles del Proyecto",
      carouselPrev: "Anterior",
      carouselNext: "Siguiente",
      items: {
        villaChukumDesc: "Una villa de lujo de 450m² oculta en la selva profunda de Tulum. El 100% de los muros interiores y exteriores fueron terminados en Chukum fino (resina de árbol endémico combinada con piedra caliza), logrando un color arena cálido que no requiere pintura y regula la temperatura de manera natural.",
        casaTzalamDesc: "Diseño asimétrico enfocado en grandes luces y terrazas en cantiléver. La calidez de la madera de Tzalam certificada localmente crea un contraste exquisito con los masivos muros de concreto aparente lavado con sascab (polvo de piedra caliza local).",
        cenoteSanctuaryDesc: "Un hito de ingeniería estructural adaptado a la geología kárstica de la región. El proyecto flota sobre pilotes de concreto armado de alta densidad para respetar el flujo subterráneo de un cenote adyacente y asegurar la estabilidad a largo plazo.",
        residenciaSascabDesc: "Proyecto de 350m² en fase de obra gris avanzada. Cada volumen fue desencofrado artesanalmente para dejar impresa la textura de tablones de madera en el concreto. Grandes ventanales orientados estratégicamente capturan las brisas marinas dominantes.",
        kaanVillaDesc: "Residencia frente al mar caribeño. Estructuras de alta resistencia preparadas para tormentas tropicales combinadas con paisajismo nativo que funciona como barrera dunar. Cuenta con una piscina infinita que se funde visualmente con el horizonte turquesa.",
      }
    },
    planner: {
      tagline: "Estudio de Conceptos",
      heading: "Asesoría Arquitectónica Digital",
      desc: "Configure las directrices de su lote o visión residencial. Nuestro motor inteligente, entrenado con las normativas, costos reales y materialidad del Caribe Mexicano, creará una propuesta conceptual exclusiva de pre-diseño.",
      formTitle: "Parámetros de Diseño",
      projName: "Nombre de la Propiedad / Proyecto",
      projNamePlaceholder: "ej. Villa Alquimia, Casa Selva",
      locationLabel: "Ubicación en Riviera Maya",
      areaLabel: "Área de Construcción Deseada",
      esteticaLabel: "Dirección Estética",
      fasesLabel: "Fases del Proyecto Requeridas",
      lujoLabel: "Nivel de Especificación y Lujo",
      specsLabel: "Requerimientos Específicos o Características Deseadas",
      specsPlaceholder: "ej. Quiero que la recámara principal tenga vista directa a la vegetación, un muro llorón de piedra y paneles solares integrados.",
      btnSubmit: "Iniciar Planificación Conceptual",
      btnSubmitting: "Generando Concepto...",
      savedInquiries: "Propuestas Guardadas",
      noPropTitle: "Diseño Arquitectónico en Tiempo Real",
      noPropDesc: "Introduzca los detalles de su lote o visión. Nuestro motor procesará una respuesta que fusiona el brutalismo de lujo y el ecosistema local de Quintana Roo de manera inmediata.",
      noPropCardTitle: "✓ Curaduría Tecnológica",
      noPropCardDesc: "Cada reporte incluye una estimación presupuestaria realista parametrizada para Tulum y una sugerencia noble de materiales nativos.",
      loadingTitle: "Esquematizando su Villa",
      loadingSteps: [
        "Analizando microclima and orientación solar de la Riviera Maya...",
        "Curando materiales nobles nativos (Chukum, Tzalam, Piedra Galarza)...",
        "Calculando cimentaciones de alta ingeniería para suelo kárstico...",
        "Diseñando estrategias de ventilación pasiva y eficiencia hídrica...",
        "Estructurando el presupuesto de obra detallado en fases exclusivas..."
      ],
      conceptBoard: "Concept Board AI",
      stylePrefix: "Estilo",
      downloadDossier: "Descargar Dossier PDF",
      dossierReady: "¡Dossier Listo para Descarga!",
      dossierReadyDesc: "Se ha generado la propuesta arquitectónica de pre-diseño. Se ha enviado una copia preliminar al equipo técnico de UNO Arquitectos.",
      close: "Cerrar",
      visionLabel: "Visión de Integración",
      adaptationLabel: "Adaptación Arquitectónica",
      materialsLabel: "Curaduría de Materiales Sugeridos",
      sustainabilityLabel: "Eco-Ingeniería Tropical Pasiva",
      budgetLabel: "Presupuesto de Obra Estimado",
      budgetRange: "Rango Total",
      directorsLabel: "Recomendaciones del Director de Diseño",
      ctaQuestion: "¿Desea formalizar este anteproyecto y comenzar el diseño esquemático presencial en nuestras oficinas de Tulum?",
      ctaBtn: "Agendar Reunión Técnica",
    },
    contacto: {
      tagline: "Contacto y Oficinas",
      heading: "Comience su Proyecto",
      desc: "Nuestros directores técnicos atienden citas presenciales en nuestro showroom de Tulum y oficinas de la CDMX. Ofrecemos cobertura total en toda la península de Yucatán.",
      showroomTulum: "Showroom Tulum (Sede Principal)",
      showroomTulumAddr: "Av. Boca Paila Km 4.5, Zona Costera, Tulum, Quintana Roo",
      cdmxOffice: "Oficina CDMX",
      cdmxOfficeAddr: "Campos Elíseos 385, Polanco III Secc, Miguel Hidalgo, CDMX",
      workHours: "Lunes a Sábado: 9:00 AM - 6:00 PM",
      formHeading: "Solicitud de Consulta",
      formSubheading: "Complete el formulario y agende una sesión inicial con un especialista técnico.",
      fullName: "Nombre Completo",
      fullNamePlaceholder: "ej. Arq. Eduardo Garza",
      phone: "Número Telefónico / WhatsApp",
      phonePlaceholder: "ej. +52 1 984 555 1234",
      email: "Correo Electrónico",
      emailPlaceholder: "ej. eduardo@luxuryholdings.com",
      additionalMsg: "Detalles Adicionales del Terreno o Construcción",
      additionalMsgPlaceholder: "Cuéntenos sobre la visión de su propiedad, m2 estimados, estado del lote y fechas deseadas.",
      btnSubmit: "Enviar Solicitud Técnica",
      successTitle: "Mensaje Recibido",
      successDesc: "Gracias por contactar con UNO Arquitectos Mx. Uno de nuestros Directores de Obra se comunicará con usted en menos de 24 horas hábiles.",
      successAnother: "Enviar otro mensaje",
    },
    footer: {
      desc: "Estudio independiente de arquitectura de vanguardia, ingeniería estructural y acabados de lujo tropical en la Riviera Maya.",
      sections: "Secciones",
      presence: "Presencia",
      attention: "Atención",
      attentionDesc: "Para programar visitas técnicas a obras activas o lotes, por favor remita su propuesta mediante la Solicitud Técnica o contacte por correo.",
      scrollTop: "Volver al inicio",
      privacy: "Aviso de Privacidad",
      terms: "Términos de Servicio",
      rights: "Todos los derechos reservados.",
    }
  },
  en: {
    nav: {
      inicio: "Home",
      filosofia: "Philosophy",
      servicios: "Elite Services",
      portfolio: "Portfolio",
      planner: "AI Advisor",
      contacto: "Contact",
    },
    hero: {
      tagline: "Tropical Brutalist Architecture & High Engineering",
      heading: "UNO Arquitectos",
      subheading: "Premium residential design and construction in the Mexican Caribbean. We fuse raw concrete, native Chukum, and exotic hardwoods with earthquake-resistant foundations adapted to the karstic soil of the Riviera Maya.",
      scroll: "Scroll to explore",
      metricBuild: "Sqm Constructed",
      metricProjects: "Delivered Projects",
      metricDirectors: "Site Directors",
    },
    filosofia: {
      tagline: "Our Philosophy",
      heading: "Harmony, Matter & Solid Structure",
      p1: "UNO Arquitectos was born with the firm purpose of redefining residential luxury in the Riviera Maya. We believe that Caribbean architecture is not just a matter of external aesthetics, but an absolute symbiosis between formal art, ecosystemic respect, and the precision of high structural engineering.",
      p2: "Our designs integrate ancestral Mayan techniques such as the fine Chukum finish and the use of certified local noble woods (Tzalam and Parota) with modern exposed reinforced concrete walls. Each volume is projected to maximize passive ventilation, capture filtered natural lighting, and coexist in equilibrium with the dense humid jungle and sea breezes.",
      p3: "Beyond the visual, we guarantee the eternal durability of your heritage. We calculate and execute seismic-resistant foundations and special piling systems designed specifically for the complex karstic subsoil of the peninsula, rigorously respecting underground rivers and local hydrology.",
      valSust: "Sustainability",
      valSustDesc: "Passive thermal comfort strategies, high-efficiency rainwater harvesting, and clean solar panels.",
      valIntegr: "Natural Integration",
      valIntegrDesc: "Total respect for the jungle topography and careful relocation of the local endemic flora.",
      valIng: "High Engineering",
      valIngDesc: "Structures capable of resisting Category 5 hurricane-force winds and stable foundations over cenotes.",
    },
    servicios: {
      tagline: "Our Phases of Work",
      heading: "Technical Services",
      desc: "We provide integrated management from high-engineering foundation to turnkey handover. Each stage is coordinated by technical directors with over 15 years of experience.",
      phases: {
        f1: "Structural Works",
        f1Desc: "Geological analysis of karstic soil, dynamic load calculation, and earthquake-resistant foundations with deep piles.",
        f2: "Gray Shell Work",
        f2Desc: "Elevation of volumes in high-specification exposed concrete. Textured castings with wood board formwork.",
        f3: "Luxury Finishes",
        f3Desc: "Artisanal application of Chukum, fine carpentry in weather-resistant tropical woods (Tzalam/Parota), and warm lighting.",
        f4: "Turnkey Handover",
        f4Desc: "Premium kitchen equipment, integrated home automation, native dune regeneration landscaping, and 360° formal handover.",
      },
      cta: "Plan My Project",
    },
    portfolio: {
      tagline: "Featured Works",
      heading: "Avant-Garde Architecture Portfolio",
      desc: "Explore our properties in the Riviera Maya. Each project represents a landmark of natural integration and material sophistication.",
      all: "All Projects",
      f_estructural: "Structural Phase",
      f_gris: "Gray Shell Work",
      f_acabados: "Luxury Finishes",
      f_entregado: "Delivered Projects",
      location: "Location",
      year: "Project Year",
      status: "Project Status",
      viewDetails: "View Project Details",
      carouselPrev: "Previous",
      carouselNext: "Next",
      items: {
        villaChukumDesc: "A 450sqm luxury villa hidden deep in the Tulum jungle. 100% of the interior and exterior walls were finished in fine Chukum (endemic tree resin combined with limestone), achieving a warm sand color that requires no paint and regulates temperature naturally.",
        casaTzalamDesc: "Asymmetric design focused on large spans and cantilevered terraces. The warmth of certified local Tzalam wood creates an exquisite contrast with the massive sascab-washed (local limestone powder) exposed concrete walls.",
        cenoteSanctuaryDesc: "A milestone in structural engineering adapted to the region's karstic geology. The project floats on high-density reinforced concrete piles to respect the underground flow of an adjacent cenote and ensure long-term stability.",
        residenciaSascabDesc: "350sqm project in advanced gray shell phase. Each volume was artisanally stripped of its formwork to leave the texture of wooden planks printed on the concrete. Strategically oriented large windows capture dominant sea breezes.",
        kaanVillaDesc: "Oceanfront residence facing the Caribbean Sea. High-resistance structures prepared for tropical storms combined with native landscaping that works as a dune barrier. Features an infinity pool that visually merges with the turquoise horizon.",
      }
    },
    planner: {
      tagline: "Concept Study",
      heading: "Digital Architectural Advisory",
      desc: "Configure the guidelines of your plot or residential vision. Our smart engine, trained with the regulations, real costs, and materiality of the Mexican Caribbean, will create an exclusive pre-design conceptual proposal.",
      formTitle: "Design Parameters",
      projName: "Property / Project Name",
      projNamePlaceholder: "e.g., Villa Alquimia, Casa Selva",
      locationLabel: "Location in Riviera Maya",
      areaLabel: "Desired Building Area",
      esteticaLabel: "Aesthetic Direction",
      fasesLabel: "Required Project Phases",
      lujoLabel: "Specification & Luxury Level",
      specsLabel: "Specific Requirements or Desired Features",
      specsPlaceholder: "e.g., I want the master bedroom to have a direct view of the vegetation, a stone weeping wall, and integrated solar panels.",
      btnSubmit: "Start Conceptual Planning",
      btnSubmitting: "Generating Concept...",
      savedInquiries: "Saved Proposals",
      noPropTitle: "Real-Time Architectural Design",
      noPropDesc: "Enter the details of your lot or vision. Our engine will process a response that immediately fuses luxury brutalism and the local ecosystem of Quintana Roo.",
      noPropCardTitle: "✓ Technological Curation",
      noPropCardDesc: "Each report includes a realistic cost estimate parameterized for Tulum and a noble selection of suggested native materials.",
      loadingTitle: "Sketching Your Villa",
      loadingSteps: [
        "Analyzing microclimate and solar orientation of the Riviera Maya...",
        "Curation of noble native materials (Chukum, Tzalam, Galarza Stone)...",
        "Calculating high-engineering foundations for karstic soil...",
        "Designing passive ventilation and water efficiency strategies...",
        "Structuring the detailed construction budget in exclusive phases..."
      ],
      conceptBoard: "AI Concept Board",
      stylePrefix: "Style",
      downloadDossier: "Download PDF Dossier",
      dossierReady: "Dossier Ready for Download!",
      dossierReadyDesc: "The pre-design architectural proposal has been generated. A preliminary copy has been forwarded to the UNO Arquitectos technical team.",
      close: "Close",
      visionLabel: "Integration Vision",
      adaptationLabel: "Architectural Adaptation",
      materialsLabel: "Suggested Materials Curation",
      sustainabilityLabel: "Passive Tropical Eco-Engineering",
      budgetLabel: "Estimated Construction Budget",
      budgetRange: "Total Range",
      directorsLabel: "Design Director's Recommendations",
      ctaQuestion: "Would you like to formalize this pre-project and start the in-person schematic design at our offices in Tulum?",
      ctaBtn: "Schedule Technical Meeting",
    },
    contacto: {
      tagline: "Contact & Offices",
      heading: "Start Your Project",
      desc: "Our technical directors host in-person consultations at our Tulum showroom and CDMX offices. We offer complete coverage across the Yucatan peninsula.",
      showroomTulum: "Showroom Tulum (Headquarters)",
      showroomTulumAddr: "Av. Boca Paila Km 4.5, Zona Costera, Tulum, Quintana Roo",
      cdmxOffice: "CDMX Office",
      cdmxOfficeAddr: "Campos Elíseos 385, Polanco III Secc, Miguel Hidalgo, CDMX",
      workHours: "Monday to Saturday: 9:00 AM - 6:00 PM",
      formHeading: "Consultation Request",
      formSubheading: "Complete the form and schedule an initial session with a technical specialist.",
      fullName: "Full Name",
      fullNamePlaceholder: "e.g., Arch. Eduardo Garza",
      phone: "Phone Number / WhatsApp",
      phonePlaceholder: "e.g., +52 1 984 555 1234",
      email: "Email Address",
      emailPlaceholder: "e.g., eduardo@luxuryholdings.com",
      additionalMsg: "Additional Plot or Construction Details",
      additionalMsgPlaceholder: "Tell us about your property vision, estimated sqm, plot status, and desired timeline.",
      btnSubmit: "Submit Technical Request",
      successTitle: "Message Received",
      successDesc: "Thank you for contacting UNO Arquitectos Mx. One of our Site Directors will reach out within 24 business hours.",
      successAnother: "Send another message",
    },
    footer: {
      desc: "Independent studio of avant-garde architecture, structural engineering, and tropical luxury finishes in the Riviera Maya.",
      sections: "Sections",
      presence: "Presence",
      attention: "Attention",
      attentionDesc: "To schedule technical visits to active construction sites or plots, please submit your proposal via the Technical Request or contact us by email.",
      scrollTop: "Back to top",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      rights: "All rights reserved.",
    }
  },
  it: {
    nav: {
      inicio: "Inizio",
      filosofia: "Filosofia",
      servicios: "Servizi d'Élite",
      portfolio: "Portfolio",
      planner: "Consulente AI",
      contacto: "Contatti",
    },
    hero: {
      tagline: "Architettura Brutalista Tropicale & Alta Ingegneria",
      heading: "UNO Arquitectos",
      subheading: "Progettazione e costruzione residenziale premium nel Mar dei Caraibi messicano. Fondiamo cemento grezzo, Chukum nativo e legni tropicali pregiati con fondazioni sismo-resistenti adattate al terreno carsico della Riviera Maya.",
      scroll: "Scorri per esplorare",
      metricBuild: "Mq Costruiti",
      metricProjects: "Progetti Consegnati",
      metricDirectors: "Direttori di Cantiere",
    },
    filosofia: {
      tagline: "La Nostra Filosofia",
      heading: "Armonia, Materia & Struttura Solida",
      p1: "UNO Arquitectos è nato con il fermo proposito di ridefinire il lusso residenziale nella Riviera Maya. Crediamo che l'architettura caraibica non sia solo una questione di estetica esteriore, ma un'assoluta simbiosi tra arte formale, rispetto degli ecosistemi e precisione dell'alta ingegneria strutturale.",
      p2: "I nostri progetti integrano tecniche Maya ancestrali come la finitura in pregiato Chukum e l'uso di legni nobili locali certificati (Tzalam e Parota) con moderni muri portanti in cemento a vista. Ogni volume è studiato per massimizzare la ventilazione passiva, catturare la luce naturale filtrata e coesistere in equilibrio con la fitta giungla tropicale e le brezze marine.",
      p3: "Oltre l'aspetto visivo, garantiamo la durata eterna del vostro patrimonio. Calcoliamo ed eseguiamo fondazioni sismo-resistenti e speciali sistemi di palificazione progettati appositamente per il complesso sottosuolo carsico della penisola, rispettando rigorosamente i fiumi sotterranei e l'idrologia locale.",
      valSust: "Sostenibilità",
      valSustDesc: "Strategie di comfort termico passivo, raccolta dell'acqua piovana ad alta efficienza e pannelli solari puliti.",
      valIntegr: "Integrazione Naturale",
      valIntegrDesc: "Totale rispetto della topografia della giungla e attento reinsediamento della flora endemica locale.",
      valIng: "Alta Ingegneria",
      valIngDesc: "Strutture capaci di resistere a venti uragano di Categoria 5 e fondazioni stabili sopra i cenote.",
    },
    servicios: {
      tagline: "Le Nostre Fasi di Lavoro",
      heading: "Servizi Tecnici d'",
      desc: "Forniamo una gestione integrata, dalle fondazioni ad alta ingegneria fino alla consegna chiavi in mano. Ogni fase è coordinata da direttori tecnici con oltre 15 anni di esperienza.",
      phases: {
        f1: "Opere Strutturali",
        f1Desc: "Analisi geologica del terreno carsico, calcolo dei carichi dinamici e fondazioni antisismiche con pali profondi.",
        f2: "Lavori al Grezzo",
        f2Desc: "Elevazione dei volumi in cemento a vista ad alta specifica. Getti testurizzati con casseforme in legno dogato.",
        f3: "Finiture di Lusso",
        f3Desc: "Applicazione artigianale di Chukum, falegnameria fine in legni tropicali resistenti agli agenti atmosferici (Tzalam/Parota) e illuminazione calda.",
        f4: "Consegna Chiavi in Mano",
        f4Desc: "Elettrodomestici da cucina premium, domotica integrata, paesaggistica nativa per la rigenerazione delle dune e consegna formale a 360°.",
      },
      cta: "Pianifica il Mio Progetto",
    },
    portfolio: {
      tagline: "Opere In Evidenza",
      heading: "Portfolio di Architettura d'Avanguardia",
      desc: "Esplora le nostre proprietà nella Riviera Maya. Ciascun progetto rappresenta un punto di riferimento per integrazione naturale e raffinatezza materica.",
      all: "Tutti i Progetti",
      f_estructural: "Fase Strutturale",
      f_gris: "Lavori al Grezzo",
      f_acabados: "Finiture di Lusso",
      f_entregado: "Progetti Consegnati",
      location: "Località",
      year: "Anno di Costruzione",
      status: "Stato dei Lavori",
      viewDetails: "Visualizza Dettagli Progetto",
      carouselPrev: "Precedente",
      carouselNext: "Successivo",
      items: {
        villaChukumDesc: "Una villa di lusso di 450 mq immersa nella giungla profonda di Tulum. Il 100% delle pareti interne ed esterne è stato rifinito in pregiato Chukum (resina di albero endemico combinata con polvere di calce), ottenendo un caldo colore sabbia che non richiede verniciatura e regola naturalmente la temperatura.",
        casaTzalamDesc: "Design asimmetrico focalizzato su ampie luci e terrazze a sbalzo. Il calore del legno di Tzalam certificato locale crea uno squisito contrasto con le imponenti pareti in cemento a vista lavato con sascab (polvo di calcare locale).",
        cenoteSanctuaryDesc: "Una pietra miliare dell'ingegneria strutturale adattata alla complessa geologia carsica della regione. Il progetto galleggia su pali in cemento armato ad alta densità per rispettare il flusso sotterraneo di un cenote adiacente e garantire stabilità a lungo termine.",
        residenciaSascabDesc: "Progetto di 350 mq in fase avanzata di costruzione al grezzo. Ogni volume è stato scasserato artigianalmente per lasciare impressa sul cemento la trama delle assi di legno. Grandi finestre orientate strategicamente catturano le brezze marine dominanti.",
        kaanVillaDesc: "Residenza fronte mare affacciata sul Mar dei Caraibi. Strutture ad alta resistenza pronte per tempeste tropicali abbinate a una progettazione del paesaggio nativo che funge da barriera per la duna. Dispone di una piscina a sfioro che si fonde visivamente con l'orizzonte turchese.",
      }
    },
    planner: {
      tagline: "Studio dei Concetti",
      heading: "Consulenza Architettonica Digitale",
      desc: "Configura le linee guida del tuo lotto o della tua visione residenziale. Il nostro motore intelligente, addestrato con le normative, i costi reali e la materialità dei Caraibi messicani, creerà un'esclusiva proposta concettuale di pre-progettazione.",
      formTitle: "Parametri di Progettazione",
      projName: "Nome della Proprietà / Progetto",
      projNamePlaceholder: "es. Villa Alquimia, Casa Selva",
      locationLabel: "Posizione nella Riviera Maya",
      areaLabel: "Area di Costruzione Desiderata",
      esteticaLabel: "Direzione Estetica",
      fasesLabel: "Fasi del Progetto Richieste",
      lujoLabel: "Livello di Specifica e Lusso",
      specsLabel: "Requisiti Specifici o Caratteristiche Desiderate",
      specsPlaceholder: "es. Desidero che la camera da letto principale abbia una vista diretta sulla vegetazione, un muro d'acqua in pietra e pannelli solari integrati.",
      btnSubmit: "Avvia Pianificazione Concettuale",
      btnSubmitting: "Generazione Concetto...",
      savedInquiries: "Proposte Salvate",
      noPropTitle: "Progettazione Architettonica in Tempo Reale",
      noPropDesc: "Inserisci i dettagli del tuo lotto o della tua visione. Il nostro motore elaborerà una risposta che fonde immediatamente il brutalismo di lusso e l'ecosistema locale di Quintana Roo.",
      noPropCardTitle: "✓ Curatela Tecnologica",
      noPropCardDesc: "Ogni report include una stima realistica dei costi parametrizzata per Tulum e una selezione di materiali nativi suggeriti.",
      loadingTitle: "Abbozzando la Tua Villa",
      loadingSteps: [
        "Analisi del microclima e dell'orientamento solare della Riviera Maya...",
        "Selezione di materiali nobili locali (Chukum, Tzalam, Pietra Galarza)...",
        "Calcolo di fondazioni ad alta ingegneria per terreno carsico...",
        "Progettazione di ventilazione passiva e strategie di efficienza idrica...",
        "Strutturazione del budget dettagliato in fasi esclusive..."
      ],
      conceptBoard: "AI Concept Board",
      stylePrefix: "Stile",
      downloadDossier: "Scarica il Dossier PDF",
      dossierReady: "Dossier Pronto per il Download!",
      dossierReadyDesc: "La proposta architettonica di pre-progettazione è stata generata. Una copia preliminare è stata inviata al team tecnico di UNO Arquitectos.",
      close: "Chiudi",
      visionLabel: "Visione d'Integrazione",
      adaptationLabel: "Adattamento Architettonico",
      materialsLabel: "Selezione dei Materiali Suggeriti",
      sustainabilityLabel: "Eco-Ingegneria Tropicale Passiva",
      budgetLabel: "Stima del Budget di Costruzione",
      budgetRange: "Intervallo Totale",
      directorsLabel: "Raccomandazioni del Direttore del Design",
      ctaQuestion: "Desideri formalizzare questo pre-progetto e avviare la progettazione preliminare di persona presso i nostri uffici di Tulum?",
      ctaBtn: "Pianifica Incontro Tecnico",
    },
    contacto: {
      tagline: "Contatti e Uffici",
      heading: "Inizia il Tuo Progetto",
      desc: "I nostri direttori tecnici offrono consulenze di persona presso il nostro showroom di Tulum e gli uffici di CDMX. Copertura completa in tutta la penisola dello Yucatan.",
      showroomTulum: "Showroom Tulum (Sede Principale)",
      showroomTulumAddr: "Av. Boca Paila Km 4.5, Zona Costera, Tulum, Quintana Roo",
      cdmxOffice: "Ufficio CDMX",
      cdmxOfficeAddr: "Campos Elíseos 385, Polanco III Secc, Miguel Hidalgo, CDMX",
      workHours: "Lunedì al Sabato: 9:00 - 18:00",
      formHeading: "Richiesta di Consulenza",
      formSubheading: "Completa il modulo e prenota una sessione iniziale con uno specialista tecnico.",
      fullName: "Nome Completo",
      fullNamePlaceholder: "es. Arch. Eduardo Garza",
      phone: "Numero di Telefono / WhatsApp",
      phonePlaceholder: "es. +52 1 984 555 1234",
      email: "Indirizzo Email",
      emailPlaceholder: "es. eduardo@luxuryholdings.com",
      additionalMsg: "Dettagli Aggiuntivi sul Terreno o sulla Costruzione",
      additionalMsgPlaceholder: "Parlaci della tua visione della proprietà, dei mq stimati, dello stato del lotto e dei tempi desiderati.",
      btnSubmit: "Invia Richiesta Tecnica",
      successTitle: "Messaggio Ricevuto",
      successDesc: "Grazie per aver contattato UNO Arquitectos Mx. Uno dei nostri Direttori di Cantiere ti contatterà entro 24 ore lavorative.",
      successAnother: "Invia un altro messaggio",
    },
    footer: {
      desc: "Studio indipendente di architettura d'avanguardia, ingegneria strutturale e finiture di lusso tropicale nella Riviera Maya.",
      sections: "Sezioni",
      presence: "Presenza",
      attention: "Atenzione",
      attentionDesc: "Per programmare visite tecniche a cantieri attivi o lotti, si prega di inviare la proposta tramite la Richiesta Tecnica o di contattarci via email.",
      scrollTop: "Torna su",
      privacy: "Informativa sulla Privacy",
      terms: "Termini di Servizio",
      rights: "Tutti i diritti riservati.",
    }
  },
  fr: {
    nav: {
      inicio: "Accueil",
      filosofia: "Philosophie",
      servicios: "Services d'Élite",
      portfolio: "Portfolio",
      planner: "Conseiller IA",
      contacto: "Contact",
    },
    hero: {
      tagline: "Architecture Brutaliste Tropicale & Haute Ingénierie",
      heading: "UNO Arquitectos",
      subheading: "Conception et construction résidentielles haut de gamme dans les Caraïbes mexicaines. Nous fusionnons béton brut, Chukum indigène et bois exotiques avec des fondations parasismiques adaptées au sol karstique de la Riviera Maya.",
      scroll: "Faites défiler pour explorer",
      metricBuild: "M² Construits",
      metricProjects: "Projets Livrés",
      metricDirectors: "Directeurs de Chantier",
    },
    filosofia: {
      tagline: "Notre Philosophie",
      heading: "Harmonie, Matière & Structure Solide",
      p1: "UNO Arquitectos est né avec la ferme intention de redéfinir le luxe résidentiel dans la Riviera Maya. Nous pensons que l'architecture caribéenne n'est pas qu'une question d'esthétique extérieure, mais une symbiose absolue entre l'art formel, le respect de l'écosystème et la précision de la haute ingénierie structurelle.",
      p2: "Nos designs intègrent des techniques mayas ancestrales telles que la finition de Chukum fin et l'utilisation de bois nobles locaux certifiés (Tzalam et Parota) avec des murs modernes en béton armé apparent. Chaque volume est projeté pour maximiser la ventilation passive, capter la lumière naturelle filtrée et coexister en équilibre avec la jungle humide et les brises marines.",
      p3: "Au-delà du visuel, nous garantissons la durabilité éternelle de votre patrimoine. Nous calculons et exécutons des fondations résistantes aux séismes et des systèmes de pilotis spéciaux conçus spécifiquement pour le sous-sol karstique complexe de la péninsule, en respectant rigoureusement les rivières souterraines et l'hydrologie locale.",
      valSust: "Durabilité",
      valSustDesc: "Stratégies de confort thermique passif, collecte des eaux de pluie à haute efficacité et panneaux solaires propres.",
      valIntegr: "Intégration Naturelle",
      valIntegrDesc: "Respect total de la topographie de la jungle et relocalisation soignée de la flore endémique locale.",
      valIng: "Haute Ingénierie",
      valIngDesc: "Structures capables de résister à des vents cycloniques de catégorie 5 et fondations stables sur les cénotes.",
    },
    servicios: {
      tagline: "Nos Phases de Travaux",
      heading: "Services Techniques d",
      desc: "Nous assurons une gestion intégrée, des fondations de haute ingénierie jusqu'à la remise des clés. Chaque étape est coordonnée par des directeurs techniques ayant plus de 15 ans d'expérience.",
      phases: {
        f1: "Travaux Structurels",
        f1Desc: "Analyse géologique du sol karstique, calcul des charges dynamiques et fondations parasismiques sur pieux profonds.",
        f2: "Gros Œuvre",
        f2Desc: "Élévation des volumes en béton apparent de haute spécification. Coulages texturés avec coffrages en planches de bois.",
        f3: "Finitions de Luxe",
        f3Desc: "Application artisanale de Chukum, menuiserie fine en bois tropicaux résistants aux intempéries (Tzalam/Parota) et éclairage chaleureux.",
        f4: "Remise Clés en Main",
        f4Desc: "Équipement de cuisine haut de gamme, domotique intégrée, aménagement paysager de régénération dunaire indigène et livraison formelle à 360°.",
      },
      cta: "Planifier Mon Projet",
    },
    portfolio: {
      tagline: "Œuvres Remarquables",
      heading: "Portfolio d'Architecture d'Avant-Garde",
      desc: "Explorez nos propriétés dans la Riviera Maya. Chaque projet représente un jalon d'intégration naturelle et de sophistication matérielle.",
      all: "Tous les Projets",
      f_estructural: "Phase Structurelle",
      f_gris: "Gros Œuvre",
      f_acabados: "Finitions de Luxe",
      f_entregado: "Projets Livrés",
      location: "Localisation",
      year: "Année de Chantier",
      status: "État des Travaux",
      viewDetails: "Voir les Détails du Projet",
      carouselPrev: "Précédent",
      carouselNext: "Suivant",
      items: {
        villaChukumDesc: "Une villa de luxe de 450 m² cachée dans la jungle profonde de Tulum. 100% des murs intérieurs et extérieurs ont été finis en Chukum fin (résine d'arbre endémique associée à de la pierre calcaire), offrant une couleur sable chaleureuse qui ne nécessite aucune peinture et régule naturellement la température.",
        casaTzalamDesc: "Design asimétrique axé sur de grandes portées et des terrasses en porte-à-faux. La chaleur du bois de Tzalam certifié local crée un contraste exquis avec les murs massifs en béton apparent lavé au sascab (poudre de calcaire locale).",
        cenoteSanctuaryDesc: "Une étape majeure de l'ingénierie structurelle adaptée à la géologie karstique de la région. Le projet flotte sur des pieux en béton armé de haute densité pour respecter le flux souterrain d'un cénote adjacent et assurer une stabilité à long terme.",
        residenciaSascabDesc: "Projet de 350 m² en phase avancée de gros œuvre. Chaque volume a été décoffré de manière artisanale pour laisser l'empreinte des planches de bois gravée sur le béton. De grandes fenêtres orientées stratégiquement captent les brises marines dominantes.",
        kaanVillaDesc: "Résidence en bord de mer face à la mer des Caraïbes. Des structures à haute résistance conçues pour les tempêtes tropicales combinées à un aménagement paysager indigène qui sert de barrière dunaire. Dispose d'une piscine à débobement qui se fond visuellement avec l'horizon turquoise.",
      }
    },
    planner: {
      tagline: "Étude des Concepts",
      heading: "Conseil Architectural Digital",
      desc: "Configurez les directives de votre terrain ou de votre vision résidentielle. Notre moteur intelligent, formé aux réglementations, aux coûts réels et à la matérialité des Caraïbes mexicaines, créera une proposition conceptuelle d'avant-projet.",
      formTitle: "Paramètres de Conception",
      projName: "Nom de la Propriété / Projet",
      projNamePlaceholder: "ex. Villa Alquimia, Casa Selva",
      locationLabel: "Localisation dans la Riviera Maya",
      areaLabel: "Surface de Construction Souhaitée",
      esteticaLabel: "Orientation Esthétique",
      fasesLabel: "Phases du Projet Requises",
      lujoLabel: "Niveau de Spécification et de Luxe",
      specsLabel: "Exigences Spécifiques ou Caractéristiques Souhaitées",
      specsPlaceholder: "ex. Je souhaite que la chambre principale ait une vue directe sur la végétation, un mur d'eau en pierre et des panneaux solaires intégrés.",
      btnSubmit: "Lancer la Planification Conceptuelle",
      btnSubmitting: "Génération du Concept...",
      savedInquiries: "Propositions Enregistrées",
      noPropTitle: "Conception Architecturale en Temps Réel",
      noPropDesc: "Saisissez les détails de votre lot ou de votre vision. Notre moteur élaborera une réponse qui fusionne immédiatement le brutalisme de luxe et l'écosystème local de Quintana Roo.",
      noPropCardTitle: "✓ Sélection Technologique",
      noPropCardDesc: "Chaque rapport comprend une estimation réaliste des coûts paramétrée pour Tulum et une sélection de matériaux locaux suggérés.",
      loadingTitle: "Esquisse de Votre Villa",
      loadingSteps: [
        "Analyse du microclimat et de l'orientation solaire de la Riviera Maya...",
        "Sélection de matériaux locaux nobles (Chukum, Tzalam, Pierre Galarza)...",
        "Calcul de fondations de haute ingénierie pour sol karstique...",
        "Conception de la ventilation passive et stratégies d'efficacité hídrica...",
        "Structuration du budget détaillé de construction en phases exclusives..."
      ],
      conceptBoard: "AI Concept Board",
      stylePrefix: "Style",
      downloadDossier: "Télécharger le Dossier PDF",
      dossierReady: "Dossier Prêt pour le Téléchargement !",
      dossierReadyDesc: "La proposition d'avant-projet architectural a été générée. Une copie préliminaire a été transmise à l'équipe technique d'UNO Arquitectos.",
      close: "Fermer",
      visionLabel: "Vision d'Intégration",
      adaptationLabel: "Adaptation Architecturale",
      materialsLabel: "Sélection des Matériaux Suggérés",
      sustainabilityLabel: "Éco-Ingénierie Tropicale Passive",
      budgetLabel: "Budget de Construction Estimé",
      budgetRange: "Fourchette Totale",
      directorsLabel: "Recommandations du Directeur du Design",
      ctaQuestion: "Souhaitez-vous formaliser cet avant-projet et commencer la conception préliminaire en personne dans nos bureaux de Tulum ?",
      ctaBtn: "Planifier une Réunion Technique",
    },
    contacto: {
      tagline: "Contact et Bureaux",
      heading: "Commencer Votre Projet",
      desc: "Nos directeurs techniques vous accueillent pour des consultations en personne dans notre showroom de Tulum et nos bureaux de CDMX. Couverture totale sur toute la péninsule du Yucatan.",
      showroomTulum: "Showroom Tulum (Siège Principal)",
      showroomTulumAddr: "Av. Boca Paila Km 4.5, Zone Cotière, Tulum, Quintana Roo",
      cdmxOffice: "Bureau CDMX",
      cdmxOfficeAddr: "Campos Elíseos 385, Polanco III Secc, Miguel Hidalgo, CDMX",
      workHours: "Lundi au Samedi : 9h00 - 18h00",
      formHeading: "Demande de Consultation",
      formSubheading: "Remplissez le formulaire et planifiez une première séance avec un spécialiste technique.",
      fullName: "Nom Complet",
      fullNamePlaceholder: "ex. Arch. Eduardo Garza",
      phone: "Numéro de Téléphone / WhatsApp",
      phonePlaceholder: "ex. +52 1 984 555 1234",
      email: "Adresse E-mail",
      emailPlaceholder: "ex. eduardo@luxuryholdings.com",
      additionalMsg: "Détails Supplémentaires sur le Terrain ou la Construction",
      additionalMsgPlaceholder: "Parlez-nous de votre vision de la propriété, de la surface estimée, de l'état du lot et des délais souhaités.",
      btnSubmit: "Envoyer la Demande Technique",
      successTitle: "Message Reçu",
      successDesc: "Merci d'avoir contacté UNO Arquitectos Mx. Un de nos Directeurs de Chantier vous contactera sous 24 heures ouvrables.",
      successAnother: "Envoyer un autre message",
    },
    footer: {
      desc: "Studio indépendant d'architecture d'avant-garde, d'ingénierie structurelle et de finitions de luxe tropical dans la Riviera Maya.",
      sections: "Présence",
      presence: "Présence",
      attention: "Attention",
      attentionDesc: "Pour planifier des visites techniques sur des chantiers actifs ou des terrains, veuillez soumettre votre proposition via la Demande Technique ou nous contacter par e-mail.",
      scrollTop: "Retour en haut",
      privacy: "Politique de Confidentialité",
      terms: "Conditions d'Utilisation",
      rights: "Tous droits réservés.",
    }
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("uno_arquitectos_lang");
    if (saved && ["es", "en", "it", "fr"].includes(saved)) {
      return saved as Language;
    }
    return "es";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("uno_arquitectos_lang", lang);
  };

  const t = (keyPath: string) => {
    const keys = keyPath.split(".");
    let current: any = TRANSLATIONS[language];
    for (const key of keys) {
      if (current && key in current) {
        current = current[key];
      } else {
        // Fallback to Spanish if translation doesn't exist
        let fb: any = TRANSLATIONS["es"];
        for (const k of keys) {
          if (fb && k in fb) {
            fb = fb[k];
          } else {
            return keyPath;
          }
        }
        return fb;
      }
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
